default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 25
  host: 127.0.0.1
  port: 3306
  reaping_frequency:
  username: root
  password: ''

development:
  database: intfarmlaunch_development
  <<: *default

test:
  database: intfarmlaunch_test
  <<: *default


production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
